# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project Information
site_name: Slugbotics
site_url: https://slugbotics.com/
site_author: Julia Barbera
site_description: >-
  UC Santa Cruz's robotics research team.


# Repository
repo_name: Slugbotics/slugbotics-material
repo_url: https://github.com/Slugbotics/slugbotics-material#

# Copyright
copyright: Copyright &copy 2025 Regents of the University of California. This group is open to all students consistent with state and federal law, the UC Nondiscrimination Statement and the Nondiscrimination Policy Statement for University of California Publications Regarding Student-Related Matters.  

theme:
  name: material
  # custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/slugbotics-logo.svg
  logo: assets/slugbotics-logo.svg

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Slugbotics
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@slugbotics866
    - icon: fontawesome/brands/discord
      link: http://discord.slugbotics.com/

nav:
  - Home: index.md
  - About: about.md
  - Projects:
    - Arm: projects/arm.md
    - Business: projects/business.md
    - Combat Robotics: projects/combatrobotics.md
    - Cruz Control: projects/cruzcontrol.md
    - Humanoid: projects/humanoid.md
    - Mate: projects/mate.md
    - Railspeeder: projects/railspeeder.md
    - Rover: projects/rover.md
    - SOMARS: projects/somars.md
  - Team: team.md
  - Onboarding: onboarding.md
  - Sponsors: sponsors.md
  - Contact: contact.md

extra_css:
  - stylesheets/extra.css
